### ISSUE TITLE
Last table in each control family not displaying in fedramp-moderate

### ISSUE THREAD

**Issue by brasky** [trevorbryant/fedramp-ssp#4]
http://fedramp-ssp.netlify.com/fedramp_moderate/

Last control in each family is not displaying as a table. For example, AC-22, AT-4, AU-12, etc. Control implementation table ends up looking like this:

|AU-12 What is the solution and how is it implemented?| |—| |Part a| |Part b| |Part c| — title: Security Assessment and Authorization (CA) —

It's previewing properly in my md previewer locally, so it might be a problem with the renderer where it's hosted which I'm less familiar with.

**Comment by trevorbryant** [comment]
I realized there's a presentation difference between my reader (Atom w/ MarkdownPreview) and GitHub's Markdown flavor.

I pushed an update resolving some tags that weren't properly closed. I've merged your PR.
